Create New Branch and Added Files
Softechbengaluru/walletwave pull request #12
Opened 2024-08-24 17:04 UTC by Madhava1104

2024-08-24 17:35 UTC, JayanthSL approved these changes

2024-08-24 17:36 UTC, JayanthSL requested changes
Make sure Design as per requirement

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/contact_select.dart
> +            color: Appearance.deepmulberry,
Make in single line

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/contact_select.dart
>                      fontWeight: FontWeight.bold,
Use between w100-900

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/contact_select.dart
> +                    color: Appearance.darkeggplant,
Single line

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/contact_select.dart
> +                          style: TextStyle(color: Colors.white70),
Use appearance

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/contact_select.dart
> +            color: Appearance.ericblack,
Use dimensions

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/contact_select.dart
>          icon: const Icon(Icons.add),
Use string

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/home_screen.dart
>      final balanceFuture = context.findAncestorStateOfType<_HomeScreenState>()?._balanceFuture;
Use question mark from string

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/home_screen.dart
>                    color: Color(getColorHexFromStr('#FDD148')),
Use appearance

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/home_screen.dart
>                    color: Color(getColorHexFromStr('#FDD148')),
Use dimensions

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/home_screen.dart
>                        color: Color(getColorHexFromStr('#FEE16D')).withOpacity(0.4),
Use appearance n dimensions

2024-08-25 11:41 UTC, JayanthSL commented on lib/screens/home_screen.dart
>                        color: Color(getColorHexFromStr('#FEE16D')).withOpacity(0.5),
Use dimensions n appearance

2024-08-25 14:31 UTC, Madhava1104 commented on lib/screens/contact_select.dart
>                      fontWeight: FontWeight.bold,
This how to do it???

2024-08-25 14:31 UTC, Madhava1104 commented on lib/screens/contact_select.dart
> +            color: Appearance.deepmulberry,
Done

2024-08-25 14:32 UTC, Madhava1104 commented on lib/screens/contact_select.dart
> +                    color: Appearance.darkeggplant,
Done

2024-08-25 14:32 UTC, Madhava1104 commented on lib/screens/contact_select.dart
> +                          style: TextStyle(color: Colors.white70),
Done

2024-08-25 14:32 UTC, Madhava1104 commented on lib/screens/contact_select.dart
> +            color: Appearance.ericblack,
Done

2024-08-25 14:33 UTC, Madhava1104 commented on lib/screens/home_screen.dart
>                        color: Color(getColorHexFromStr('#FEE16D')).withOpacity(0.5),
Done

2024-08-25 14:33 UTC, Madhava1104 commented on lib/screens/home_screen.dart
>                    color: Color(getColorHexFromStr('#FDD148')),
Double Infinity How to give in dimensions?

2024-08-25 14:33 UTC, Madhava1104 commented on lib/screens/home_screen.dart
>                    color: Color(getColorHexFromStr('#FDD148')),
Done

2024-08-25 14:34 UTC, Madhava1104 commented on lib/screens/home_screen.dart
>      final balanceFuture = context.findAncestorStateOfType<_HomeScreenState>()?._balanceFuture;
After paranthesis , question mark is there no that one?? (   ()?._balanceFuture  )

2024-08-25 14:34 UTC, Madhava1104 commented on lib/screens/contact_select.dart
>          icon: const Icon(Icons.add),
How??

2024-08-25 14:57 UTC, JayanthSL commented on lib/screens/contact_select.dart
>                      fontWeight: FontWeight.bold,
Fontweight.w600

2024-08-25 15:00 UTC, JayanthSL commented on lib/widgets/appearance.dart
> +  static Color deepblue = const Color(0xFF290164);
Remove all these don't change appearance.dart file

2024-08-25 15:05 UTC, JayanthSL commented on lib/screens/contact_select.dart
> +                    color: Color(0x80B0B0B0),
Use dimensions

2024-08-25 15:05 UTC, JayanthSL commented on lib/screens/contact_select.dart
> +              margin: const EdgeInsets.symmetric(horizontal: 16.0),
Dimensions

2024-08-25 15:05 UTC, JayanthSL commented on lib/screens/sendmoney.dart
> +      extendBodyBehindAppBar: true, // Make sure the scaffold extends behind the app bar
Remove comments bc chatgpt

2024-08-26 09:18 UTC, JayanthSL approved these changes

2024-08-26 11:36 UTC, JayanthSL approved these changes

2024-08-26 11:39 UTC, Madhava1104 reviewed
Reviewed

2024-08-26 12:05 UTC, JayanthSL approved these changes

2024-08-26 12:30 UTC, JayanthSL approved these changes

2024-08-26 13:58 UTC, closed without merging